# Generated by Django 3.2.18 on 2023-03-16 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='post',
        ),
    ]
